FROM node:alpine AS frontend

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build  # Assuming you use npm run build for production build

EXPOSE 80

FROM nginx:alpine

COPY --from=frontend /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
