# Use an appropriate base image 
FROM azul/zulu-openjdk-alpine:17
# Setting the working directory within the container
WORKDIR /app

# Copying the JAR file into the container 
COPY UniverseUpClose/mynasaapp/target/mynasaapp-0.0.1-SNAPSHOT.jar app.jar

# Exposing the port the application will run on
EXPOSE 8080

# Command to run the application when the container starts
CMD ["java", "-jar", "app.jar"]



